export interface Country {
  code: string; // ISO 3166-1 alpha-2, uppercase
  en: string;   // English name (ISO short name)
  th: string;   // Thai name
}

// All countries, sorted alphabetically by English name.
export const COUNTRIES: Country[] = [
  { code: "AF", en: "Afghanistan", th: "อัฟกานิสถาน" },
  { code: "AL", en: "Albania", th: "แอลเบเนีย" },
  { code: "DZ", en: "Algeria", th: "แอลจีเรีย" },
  { code: "AD", en: "Andorra", th: "อันดอร์รา" },
  { code: "AO", en: "Angola", th: "แองโกลา" },
  { code: "AG", en: "Antigua and Barbuda", th: "แอนติกาและบาร์บูดา" },
  { code: "AR", en: "Argentina", th: "อาร์เจนตินา" },
  { code: "AM", en: "Armenia", th: "อาร์เมเนีย" },
  { code: "AU", en: "Australia", th: "ออสเตรเลีย" },
  { code: "AT", en: "Austria", th: "ออสเตรีย" },
  { code: "AZ", en: "Azerbaijan", th: "อาเซอร์ไบจาน" },
  { code: "BS", en: "Bahamas", th: "บาฮามาส" },
  { code: "BH", en: "Bahrain", th: "บาห์เรน" },
  { code: "BD", en: "Bangladesh", th: "บังกลาเทศ" },
  { code: "BB", en: "Barbados", th: "บาร์เบโดส" },
  { code: "BY", en: "Belarus", th: "เบลารุส" },
  { code: "BE", en: "Belgium", th: "เบลเยียม" },
  { code: "BZ", en: "Belize", th: "เบลีซ" },
  { code: "BJ", en: "Benin", th: "เบนิน" },
  { code: "BT", en: "Bhutan", th: "ภูฏาน" },
  { code: "BO", en: "Bolivia", th: "โบลิเวีย" },
  { code: "BA", en: "Bosnia and Herzegovina", th: "บอสเนียและเฮอร์เซโกวีนา" },
  { code: "BW", en: "Botswana", th: "บอตสวานา" },
  { code: "BR", en: "Brazil", th: "บราซิล" },
  { code: "BN", en: "Brunei", th: "บรูไน" },
  { code: "BG", en: "Bulgaria", th: "บัลแกเรีย" },
  { code: "BF", en: "Burkina Faso", th: "บูร์กินาฟาโซ" },
  { code: "BI", en: "Burundi", th: "บุรุนดี" },
  { code: "CV", en: "Cabo Verde", th: "กาบูเวร์ดี" },
  { code: "KH", en: "Cambodia", th: "กัมพูชา" },
  { code: "CM", en: "Cameroon", th: "แคเมอรูน" },
  { code: "CA", en: "Canada", th: "แคนาดา" },
  { code: "CF", en: "Central African Republic", th: "สาธารณรัฐแอฟริกากลาง" },
  { code: "TD", en: "Chad", th: "ชาด" },
  { code: "CL", en: "Chile", th: "ชิลี" },
  { code: "CN", en: "China", th: "จีน" },
  { code: "CO", en: "Colombia", th: "โคลอมเบีย" },
  { code: "KM", en: "Comoros", th: "คอโมโรส" },
  { code: "CG", en: "Congo (Republic of the)", th: "คองโก (สาธารณรัฐ)" },
  { code: "CD", en: "Congo (Democratic Republic of the)", th: "คองโก (สาธารณรัฐประชาธิปไตย)" },
  { code: "CR", en: "Costa Rica", th: "คอสตาริกา" },
  { code: "CI", en: "Côte d'Ivoire", th: "โกตดิวัวร์" },
  { code: "HR", en: "Croatia", th: "โครเอเชีย" },
  { code: "CU", en: "Cuba", th: "คิวบา" },
  { code: "CY", en: "Cyprus", th: "ไซปรัส" },
  { code: "CZ", en: "Czechia", th: "เช็กเกีย" },
  { code: "DK", en: "Denmark", th: "เดนมาร์ก" },
  { code: "DJ", en: "Djibouti", th: "จิบูตี" },
  { code: "DM", en: "Dominica", th: "ดอมินิกา" },
  { code: "DO", en: "Dominican Republic", th: "สาธารณรัฐโดมินิกัน" },
  { code: "EC", en: "Ecuador", th: "เอกวาดอร์" },
  { code: "EG", en: "Egypt", th: "อียิปต์" },
  { code: "SV", en: "El Salvador", th: "เอลซัลวาดอร์" },
  { code: "GQ", en: "Equatorial Guinea", th: "อิเควทอเรียลกินี" },
  { code: "ER", en: "Eritrea", th: "เอริเทรีย" },
  { code: "EE", en: "Estonia", th: "เอสโตเนีย" },
  { code: "SZ", en: "Eswatini", th: "เอสวาตีนี" },
  { code: "ET", en: "Ethiopia", th: "เอธิโอเปีย" },
  { code: "FJ", en: "Fiji", th: "ฟิจิ" },
  { code: "FI", en: "Finland", th: "ฟินแลนด์" },
  { code: "FR", en: "France", th: "ฝรั่งเศส" },
  { code: "GA", en: "Gabon", th: "กาบอง" },
  { code: "GM", en: "Gambia", th: "แกมเบีย" },
  { code: "GE", en: "Georgia", th: "จอร์เจีย" },
  { code: "DE", en: "Germany", th: "เยอรมนี" },
  { code: "GH", en: "Ghana", th: "กานา" },
  { code: "GR", en: "Greece", th: "กรีซ" },
  { code: "GD", en: "Grenada", th: "เกรเนดา" },
  { code: "GT", en: "Guatemala", th: "กัวเตมาลา" },
  { code: "GN", en: "Guinea", th: "กินี" },
  { code: "GW", en: "Guinea-Bissau", th: "กินี-บิสเซา" },
  { code: "GY", en: "Guyana", th: "กายอานา" },
  { code: "HT", en: "Haiti", th: "เฮติ" },
  { code: "HN", en: "Honduras", th: "ฮอนดูรัส" },
  { code: "HK", en: "Hong Kong", th: "ฮ่องกง" },
  { code: "HU", en: "Hungary", th: "ฮังการี" },
  { code: "IS", en: "Iceland", th: "ไอซ์แลนด์" },
  { code: "IN", en: "India", th: "อินเดีย" },
  { code: "ID", en: "Indonesia", th: "อินโดนีเซีย" },
  { code: "IR", en: "Iran", th: "อิหร่าน" },
  { code: "IQ", en: "Iraq", th: "อิรัก" },
  { code: "IE", en: "Ireland", th: "ไอร์แลนด์" },
  { code: "IL", en: "Israel", th: "อิสราเอล" },
  { code: "IT", en: "Italy", th: "อิตาลี" },
  { code: "JM", en: "Jamaica", th: "จาเมกา" },
  { code: "JP", en: "Japan", th: "ญี่ปุ่น" },
  { code: "JO", en: "Jordan", th: "จอร์แดน" },
  { code: "KZ", en: "Kazakhstan", th: "คาซัคสถาน" },
  { code: "KE", en: "Kenya", th: "เคนยา" },
  { code: "KI", en: "Kiribati", th: "คิริบาส" },
  { code: "KP", en: "Korea (North)", th: "เกาหลีเหนือ" },
  { code: "KR", en: "Korea (South)", th: "เกาหลีใต้" },
  { code: "KW", en: "Kuwait", th: "คูเวต" },
  { code: "KG", en: "Kyrgyzstan", th: "คีร์กีซสถาน" },
  { code: "LA", en: "Laos", th: "ลาว" },
  { code: "LV", en: "Latvia", th: "ลัตเวีย" },
  { code: "LB", en: "Lebanon", th: "เลบานอน" },
  { code: "LS", en: "Lesotho", th: "เลโซโท" },
  { code: "LR", en: "Liberia", th: "ไลบีเรีย" },
  { code: "LY", en: "Libya", th: "ลิเบีย" },
  { code: "LI", en: "Liechtenstein", th: "ลิกเตนสไตน์" },
  { code: "LT", en: "Lithuania", th: "ลิทัวเนีย" },
  { code: "LU", en: "Luxembourg", th: "ลักเซมเบิร์ก" },
  { code: "MO", en: "Macau", th: "มาเก๊า" },
  { code: "MG", en: "Madagascar", th: "มาดากัสการ์" },
  { code: "MW", en: "Malawi", th: "มาลาวี" },
  { code: "MY", en: "Malaysia", th: "มาเลเซีย" },
  { code: "MV", en: "Maldives", th: "มัลดีฟส์" },
  { code: "ML", en: "Mali", th: "มาลี" },
  { code: "MT", en: "Malta", th: "มอลตา" },
  { code: "MH", en: "Marshall Islands", th: "หมู่เกาะมาร์แชลล์" },
  { code: "MR", en: "Mauritania", th: "มอริเตเนีย" },
  { code: "MU", en: "Mauritius", th: "มอริเชียส" },
  { code: "MX", en: "Mexico", th: "เม็กซิโก" },
  { code: "FM", en: "Micronesia", th: "ไมโครนีเซีย" },
  { code: "MD", en: "Moldova", th: "มอลโดวา" },
  { code: "MC", en: "Monaco", th: "โมนาโก" },
  { code: "MN", en: "Mongolia", th: "มองโกเลีย" },
  { code: "ME", en: "Montenegro", th: "มอนเตเนโกร" },
  { code: "MA", en: "Morocco", th: "โมร็อกโก" },
  { code: "MZ", en: "Mozambique", th: "โมซัมบิก" },
  { code: "MM", en: "Myanmar", th: "เมียนมา" },
  { code: "NA", en: "Namibia", th: "นามิเบีย" },
  { code: "NR", en: "Nauru", th: "นาอูรู" },
  { code: "NP", en: "Nepal", th: "เนปาล" },
  { code: "NL", en: "Netherlands", th: "เนเธอร์แลนด์" },
  { code: "NZ", en: "New Zealand", th: "นิวซีแลนด์" },
  { code: "NI", en: "Nicaragua", th: "นิการากัว" },
  { code: "NE", en: "Niger", th: "ไนเจอร์" },
  { code: "NG", en: "Nigeria", th: "ไนจีเรีย" },
  { code: "MK", en: "North Macedonia", th: "นอร์ทมาซิโดเนีย" },
  { code: "NO", en: "Norway", th: "นอร์เวย์" },
  { code: "OM", en: "Oman", th: "โอมาน" },
  { code: "PK", en: "Pakistan", th: "ปากีสถาน" },
  { code: "PW", en: "Palau", th: "ปาเลา" },
  { code: "PS", en: "Palestine", th: "ปาเลสไตน์" },
  { code: "PA", en: "Panama", th: "ปานามา" },
  { code: "PG", en: "Papua New Guinea", th: "ปาปัวนิวกินี" },
  { code: "PY", en: "Paraguay", th: "ปารากวัย" },
  { code: "PE", en: "Peru", th: "เปรู" },
  { code: "PH", en: "Philippines", th: "ฟิลิปปินส์" },
  { code: "PL", en: "Poland", th: "โปแลนด์" },
  { code: "PT", en: "Portugal", th: "โปรตุเกส" },
  { code: "QA", en: "Qatar", th: "กาตาร์" },
  { code: "RO", en: "Romania", th: "โรมาเนีย" },
  { code: "RU", en: "Russia", th: "รัสเซีย" },
  { code: "RW", en: "Rwanda", th: "รวันดา" },
  { code: "KN", en: "Saint Kitts and Nevis", th: "เซนต์คิตส์และเนวิส" },
  { code: "LC", en: "Saint Lucia", th: "เซนต์ลูเชีย" },
  { code: "VC", en: "Saint Vincent and the Grenadines", th: "เซนต์วินเซนต์และเกรนาดีนส์" },
  { code: "WS", en: "Samoa", th: "ซามัว" },
  { code: "SM", en: "San Marino", th: "ซานมารีโน" },
  { code: "ST", en: "Sao Tome and Principe", th: "เซาตูเมและปรินซีปี" },
  { code: "SA", en: "Saudi Arabia", th: "ซาอุดีอาระเบีย" },
  { code: "SN", en: "Senegal", th: "เซเนกัล" },
  { code: "RS", en: "Serbia", th: "เซอร์เบีย" },
  { code: "SC", en: "Seychelles", th: "เซเชลส์" },
  { code: "SL", en: "Sierra Leone", th: "เซียร์ราลีโอน" },
  { code: "SG", en: "Singapore", th: "สิงคโปร์" },
  { code: "SK", en: "Slovakia", th: "สโลวาเกีย" },
  { code: "SI", en: "Slovenia", th: "สโลวีเนีย" },
  { code: "SB", en: "Solomon Islands", th: "หมู่เกาะโซโลมอน" },
  { code: "SO", en: "Somalia", th: "โซมาเลีย" },
  { code: "ZA", en: "South Africa", th: "แอฟริกาใต้" },
  { code: "SS", en: "South Sudan", th: "เซาท์ซูดาน" },
  { code: "ES", en: "Spain", th: "สเปน" },
  { code: "LK", en: "Sri Lanka", th: "ศรีลังกา" },
  { code: "SD", en: "Sudan", th: "ซูดาน" },
  { code: "SR", en: "Suriname", th: "ซูรินาเม" },
  { code: "SE", en: "Sweden", th: "สวีเดน" },
  { code: "CH", en: "Switzerland", th: "สวิตเซอร์แลนด์" },
  { code: "SY", en: "Syria", th: "ซีเรีย" },
  { code: "TW", en: "Taiwan", th: "ไต้หวัน" },
  { code: "TJ", en: "Tajikistan", th: "ทาจิกิสถาน" },
  { code: "TZ", en: "Tanzania", th: "แทนซาเนีย" },
  { code: "TH", en: "Thailand", th: "ไทย" },
  { code: "TL", en: "Timor-Leste", th: "ติมอร์-เลสเต" },
  { code: "TG", en: "Togo", th: "โตโก" },
  { code: "TO", en: "Tonga", th: "ตองงา" },
  { code: "TT", en: "Trinidad and Tobago", th: "ตรินิแดดและโตเบโก" },
  { code: "TN", en: "Tunisia", th: "ตูนิเซีย" },
  { code: "TR", en: "Turkey", th: "ตุรกี" },
  { code: "TM", en: "Turkmenistan", th: "เติร์กเมนิสถาน" },
  { code: "TV", en: "Tuvalu", th: "ตูวาลู" },
  { code: "UG", en: "Uganda", th: "ยูกันดา" },
  { code: "UA", en: "Ukraine", th: "ยูเครน" },
  { code: "AE", en: "United Arab Emirates", th: "สหรัฐอาหรับเอมิเรตส์" },
  { code: "GB", en: "United Kingdom", th: "สหราชอาณาจักร" },
  { code: "US", en: "United States", th: "สหรัฐอเมริกา" },
  { code: "UY", en: "Uruguay", th: "อุรุกวัย" },
  { code: "UZ", en: "Uzbekistan", th: "อุซเบกิสถาน" },
  { code: "VU", en: "Vanuatu", th: "วานูอาตู" },
  { code: "VA", en: "Vatican City", th: "นครรัฐวาติกัน" },
  { code: "VE", en: "Venezuela", th: "เวเนซุเอลา" },
  { code: "VN", en: "Vietnam", th: "เวียดนาม" },
  { code: "YE", en: "Yemen", th: "เยเมน" },
  { code: "ZM", en: "Zambia", th: "แซมเบีย" },
  { code: "ZW", en: "Zimbabwe", th: "ซิมบับเว" },
];

/** Flag emoji from an ISO alpha-2 code (regional-indicator letters). */
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/[^A-Z]/g, "")
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}
