-- =====================================================================
-- 0003 — Seed visa_questionnaire (36 questions, the question catalog).
--
-- Reconstructed verbatim from the live itinerry-webapp DB (already seeded there
-- on 2026-06-28). The app renders questions from lib/questions.ts; this catalog
-- mirrors them for the DB side. legacy_id maps each row to the app's q-id.
-- =====================================================================

insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('consent', 'q2', 'ข้าพเจ้าขอรับรองว่าข้อมูลทั้งหมดในแบบฟอร์มนี้เป็นความจริงและถูกต้องทุกประการ', 'I certify that all information in this form is true and accurate.', 'consent', 'S0', 1, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('full_name', 'q3', 'ชื่อ-นามสกุล', 'Full Name', 'text', 'S1', 2, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('nationality', 'q4', 'สัญชาติ', 'Nationality', 'radio', 'S1', 3, '''[{"emoji": "🇹🇭", "value": "thai", "label_en": "Thai", "label_th": "ไทย"}, {"emoji": "🌍", "value": "other", "label_en": "Other", "label_th": "อื่นๆ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('phone', 'q5', 'เบอร์โทรศัพท์', 'Phone Number', 'tel', 'S1', 4, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('email', 'q6', 'อีเมล (สำหรับรับเอกสารตอนให้บริการ)', 'Email (for receiving documents)', 'email', 'S1', 5, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('source', 'q7', 'รู้จัก itinerry จากช่องทางไหน?', 'How did you find us?', 'radio', 'S1', 6, '''[{"value": "facebook", "label_en": "Facebook", "label_th": "Facebook"}, {"value": "instagram", "label_en": "Instagram", "label_th": "Instagram"}, {"value": "tiktok", "label_en": "TikTok", "label_th": "TikTok"}, {"value": "google", "label_en": "Google", "label_th": "Google"}, {"value": "referral", "label_en": "Referral", "label_th": "เพื่อนแนะนำ"}, {"value": "other", "label_en": "Other", "label_th": "อื่นๆ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('destination', 'q8', 'ประเทศที่ต้องการยื่นวีซ่า', 'Destination Country', 'dropdown', 'S2', 7, '''[{"value": "schengen", "label_en": "Schengen / Europe", "label_th": "Schengen / ยุโรป"}, {"value": "uk", "label_en": "United Kingdom", "label_th": "United Kingdom"}, {"value": "usa", "label_en": "United States", "label_th": "United States"}, {"value": "canada", "label_en": "Canada", "label_th": "Canada"}, {"value": "australia", "label_en": "Australia", "label_th": "Australia"}, {"value": "nz", "label_en": "New Zealand", "label_th": "New Zealand"}, {"value": "japan", "label_en": "Japan", "label_th": "Japan"}, {"value": "korea", "label_en": "South Korea", "label_th": "South Korea"}, {"value": "china", "label_en": "China", "label_th": "China"}, {"value": "taiwan", "label_en": "Taiwan", "label_th": "Taiwan"}, {"value": "india", "label_en": "India", "label_th": "India"}, {"value": "dubai", "label_en": "Dubai / UAE", "label_th": "Dubai / UAE"}, {"value": "saudi", "label_en": "Saudi Arabia", "label_th": "Saudi Arabia"}, {"value": "qatar", "label_en": "Qatar", "label_th": "Qatar"}, {"value": "other", "label_en": "Others", "label_th": "อื่นๆ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visa_type', 'q9', 'ประเภทวีซ่าที่ต้องการ', 'Visa Type', 'radio', 'S2', 8, '''[{"value": "tourist", "label_en": "Tourist", "label_th": "วีซ่าท่องเที่ยว"}, {"value": "visitor", "label_en": "Visitor", "label_th": "วีซ่าเยี่ยมเยียน"}, {"value": "business", "label_en": "Business", "label_th": "วีซ่าธุรกิจ"}, {"value": "student", "label_en": "Student", "label_th": "วีซ่านักเรียน"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('tourist_arrival', 'q10', 'วันที่วางแผนเดินทาง (วันแรกที่ถึงปลายทาง)', 'Planned Arrival Date', 'date', 'S2A', 9, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('tourist_return', 'q11', 'วันที่วางแผนกลับ (วันที่ออกจากประเทศปลายทาง)', 'Planned Return Date', 'date', 'S2A', 10, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('tourist_previous_visas', 'q12', 'เคยได้รับวีซ่าประเทศเหล่านี้ภายใน 5 ปีที่ผ่านมาไหม?', 'Visas received in last 5 years?', 'multiCheckbox', 'S2A', 11, '''[{"value": "never", "label_en": "Never", "label_th": "ไม่เคย"}, {"value": "uk", "label_en": "UK", "label_th": "UK"}, {"value": "schengen", "label_en": "Schengen", "label_th": "Schengen"}, {"value": "usa", "label_en": "USA", "label_th": "USA"}, {"value": "canada", "label_en": "Canada", "label_th": "Canada"}, {"value": "australia", "label_en": "Australia", "label_th": "Australia"}, {"value": "nz", "label_en": "New Zealand", "label_th": "New Zealand"}, {"value": "japan", "label_en": "Japan", "label_th": "Japan"}, {"value": "korea", "label_en": "S. Korea", "label_th": "S. Korea"}, {"value": "china", "label_en": "China", "label_th": "China"}, {"value": "dubai", "label_en": "Dubai / UAE", "label_th": "Dubai / UAE"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visitor_arrival', 'q13', 'วันที่วางแผนเดินทาง (วันแรกที่ถึงปลายทาง)', 'Planned Arrival Date', 'date', 'S2B', 12, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visitor_host_status', 'q14', 'คนที่คุณจะไปเยี่ยมมีสถานะอะไรในประเทศนั้น?', 'Immigration status of host?', 'radio', 'S2B', 13, '''[{"value": "citizen_pr", "label_en": "Citizen / PR", "label_th": "Citizen / PR"}, {"value": "work_visa", "label_en": "Work Visa", "label_th": "Work Visa"}, {"value": "student_visa", "label_en": "Student Visa", "label_th": "Student Visa"}, {"value": "not_sure", "label_en": "Not sure", "label_th": "ไม่แน่ใจ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visitor_relationship', 'q15', 'ผู้เชิญมีความสัมพันธ์รูปแบบใดกับคุณ?', 'Relationship with host?', 'radio', 'S2B', 14, '''[{"value": "family", "label_en": "Family", "label_th": "ครอบครัว"}, {"value": "relative", "label_en": "Relative", "label_th": "ญาติ"}, {"value": "married", "label_en": "Spouse (married)", "label_th": "คู่สมรส (จดทะเบียน)"}, {"value": "partner", "label_en": "Partner", "label_th": "แฟน"}, {"value": "friend", "label_en": "Friend", "label_th": "เพื่อน"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visitor_host_documents', 'q16', 'เอกสารที่ผู้เชิญสามารถส่งให้คุณได้', 'Documents host can provide', 'multiCheckbox', 'S2B', 15, '''[{"value": "invitation_letter", "label_en": "Invitation Letter", "label_th": "จดหมายเชิญ"}, {"value": "house_cert", "label_en": "House Certificate", "label_th": "หลักฐานที่พัก"}, {"value": "job_cert", "label_en": "Job Certificate", "label_th": "จดหมายรับรองงาน"}, {"value": "bank_stmt", "label_en": "Bank Statement 6m", "label_th": "รายการเดินบัญชี 6 เดือน"}, {"value": "none", "label_en": "None", "label_th": "ไม่มีเลย"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('business_arrival', 'q17', 'วันที่วางแผนเดินทาง (วันแรกที่ถึงปลายทาง)', 'Planned Arrival Date', 'date', 'S2C', 16, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('business_return', 'q18', 'วันที่วางแผนกลับ (วันที่ออกจากประเทศปลายทาง)', 'Planned Return Date', 'date', 'S2C', 17, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('business_invitation_letter', 'q19', 'มีหนังสือเชิญ (Invitation Letter) จากบริษัทในประเทศปลายทางไหม?', 'Have Invitation Letter?', 'radio', 'S2C', 18, '''[{"value": "yes", "label_en": "Yes", "label_th": "มีแล้ว"}, {"value": "requesting", "label_en": "Requesting soon", "label_th": "กำลังจะขอ"}, {"value": "not_required", "label_en": "Not required", "label_th": "ไม่ต้องการ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('business_previous_visas', 'q20', 'เคยได้รับวีซ่าประเทศเหล่านี้ภายใน 5 ปีที่ผ่านมาไหม?', 'Visas received in last 5 years?', 'multiCheckbox', 'S2C', 19, '''[{"value": "never", "label_en": "Never", "label_th": "ไม่เคย"}, {"value": "uk", "label_en": "UK", "label_th": "UK"}, {"value": "schengen", "label_en": "Schengen", "label_th": "Schengen"}, {"value": "usa", "label_en": "USA", "label_th": "USA"}, {"value": "canada", "label_en": "Canada", "label_th": "Canada"}, {"value": "australia", "label_en": "Australia", "label_th": "Australia"}, {"value": "nz", "label_en": "New Zealand", "label_th": "New Zealand"}, {"value": "japan", "label_en": "Japan", "label_th": "Japan"}, {"value": "korea", "label_en": "S. Korea", "label_th": "S. Korea"}, {"value": "china", "label_en": "China", "label_th": "China"}, {"value": "dubai", "label_en": "Dubai / UAE", "label_th": "Dubai / UAE"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('student_study_start', 'q21', 'วันที่วางแผนเริ่มเรียน (วันแรกที่เริ่มเรียน)', 'Planned Study Start Date', 'date', 'S2D', 20, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('student_acceptance_letter', 'q22', 'ได้รับ Acceptance Letter จากสถาบันแล้วไหม?', 'Have Acceptance Letter?', 'radio', 'S2D', 21, '''[{"value": "received", "label_en": "Yes, received", "label_th": "ได้รับแล้ว"}, {"value": "in_progress", "label_en": "Application in progress", "label_th": "อยู่ระหว่างสมัคร"}, {"value": "not_applied", "label_en": "Not yet applied", "label_th": "ยังไม่ได้สมัคร"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('student_expense_sponsor', 'q23', 'ใครเป็นผู้รับผิดชอบค่าใช้จ่ายในการเรียน?', 'Who sponsors study expenses?', 'radio', 'S2D', 22, '''[{"value": "self", "label_en": "Self", "label_th": "ตัวเอง"}, {"value": "parents", "label_en": "Parents", "label_th": "พ่อแม่"}, {"value": "scholarship", "label_en": "Scholarship", "label_th": "ทุนการศึกษา"}, {"value": "other", "label_en": "Other", "label_th": "อื่นๆ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('occupation', 'q24', 'อาชีพปัจจุบันของคุณคืออะไร?', 'What is your current occupation?', 'radio', 'S3', 23, '''[{"value": "employee", "label_en": "Employee", "label_th": "พนักงานประจำ"}, {"value": "government", "label_en": "Government Officer", "label_th": "ข้าราชการ"}, {"value": "freelance", "label_en": "Freelance", "label_th": "Freelance / อิสระ"}, {"value": "business_owner", "label_en": "Business Owner", "label_th": "เจ้าของธุรกิจ"}, {"value": "retired", "label_en": "Retired", "label_th": "เกษียณอายุ"}, {"value": "homemaker", "label_en": "Homemaker", "label_th": "แม่บ้าน"}, {"value": "student_occ", "label_en": "Student", "label_th": "นักเรียน/นักศึกษา"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('employee_work_letter', 'q25', 'มีหนังสือรับรองงานที่ระบุ ตำแหน่ง + เงินเดือน + วันลาไหม?', 'Employment Letter with position, salary, approved leave?', 'radio', 'S4A', 24, '''[{"value": "complete", "label_en": "Yes, complete", "label_th": "มีครบ"}, {"value": "partial", "label_en": "Partial", "label_th": "มีแต่ไม่ครบ"}, {"value": "none", "label_en": "Not yet", "label_th": "ยังไม่มี"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('freelance_income_proof', 'q26', 'มีเอกสารพิสูจน์รายได้ไหม? (สัญญา / Invoice / Bank Transfer)', 'Income proof? (Contract / Invoice / Bank Transfer)', 'radio', 'S4B', 25, '''[{"value": "all_three", "label_en": "Have all three", "label_th": "มีครบทั้งสามอย่าง"}, {"value": "partial", "label_en": "Partial", "label_th": "มีบางส่วน"}, {"value": "none", "label_en": "None", "label_th": "ไม่มีเลย"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('freelance_tax_history', 'q27', 'มีเอกสารชำระภาษีย้อนหลัง 3 ปีไหม?', 'Tax documents for last 3 years?', 'radio', 'S4B', 26, '''[{"value": "all_3y", "label_en": "Have all 3 years", "label_th": "มีครบ 3 ปี"}, {"value": "partial", "label_en": "Partial", "label_th": "มีบางส่วน"}, {"value": "none", "label_en": "None", "label_th": "ไม่มีเลย"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('business_registration', 'q28', 'มีหนังสือรับรองบริษัท (DBD) หรือเอกสารจดทะเบียนธุรกิจไหม?', 'Company Registration Certificate (DBD)?', 'radio', 'S4C', 27, '''[{"value": "yes", "label_en": "Yes", "label_th": "มีแล้ว"}, {"value": "no", "label_en": "Not yet", "label_th": "ยังไม่มี"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('dependent_expense_sponsor', 'q29', 'ใครเป็นผู้รับผิดชอบค่าใช้จ่ายในการเดินทาง?', 'Who sponsors travel expenses?', 'radio', 'S4D', 28, '''[{"value": "parents", "label_en": "Parents", "label_th": "พ่อแม่"}, {"value": "spouse", "label_en": "Spouse", "label_th": "คู่สมรส"}, {"value": "self_savings", "label_en": "Self (savings)", "label_th": "ตัวเอง (มีเงินออม)"}, {"value": "employer", "label_en": "Employer", "label_th": "บริษัท"}, {"value": "other", "label_en": "Other", "label_th": "อื่นๆ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visa_refused', 'q30', 'เคยถูกปฏิเสธวีซ่าจากประเทศใดไหม?', 'Ever been refused a visa?', 'radio', 'S5', 29, '''[{"value": "never", "label_en": "Never", "label_th": "ไม่เคย"}, {"value": "yes", "label_en": "Yes", "label_th": "เคย"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('visa_refused_details', 'q31', 'ระบุประเทศและปีที่ถูกปฏิเสธวีซ่า', 'Specify country and year of refusal', 'text', 'S5', 30, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('overstayed', 'q32', 'เคยอยู่ในประเทศใดเกินกำหนดวีซ่า (Overstay) ไหม?', 'Ever overstayed a visa?', 'radio', 'S5', 31, '''[{"value": "never", "label_en": "Never", "label_th": "ไม่เคย"}, {"value": "yes", "label_en": "Yes", "label_th": "เคย"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('overstay_details', 'q33', 'ระบุประเทศ ระยะเวลา และปีที่เกิด Overstay', 'Specify country, duration, and year', 'text', 'S5', 32, 'null', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('savings_balance', 'q34', 'ยอดเงินในบัญชีออมทรัพย์ปัจจุบันประมาณเท่าไหร่?', 'Approximate savings balance?', 'radio', 'S5', 33, '''[{"value": "under50k", "label_en": "< 50K THB", "label_th": "น้อยกว่า 50,000 บาท"}, {"value": "50k_150k", "label_en": "50–150K THB", "label_th": "50,000–150,000 บาท"}, {"value": "150k_300k", "label_en": "150–300K THB", "label_th": "150,000–300,000 บาท"}, {"value": "over300k", "label_en": "> 300K THB", "label_th": "มากกว่า 300,000 บาท"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('ties_thailand', 'q35', 'ความผูกพันกับประเทศไทย (เลือกได้มากกว่า 1)', 'Ties to Thailand (select all that apply)', 'multiCheckbox', 'S5', 34, '''[{"value": "job", "label_en": "Job or business in Thailand", "label_th": "งานประจำหรือธุรกิจในไทย"}, {"value": "property", "label_en": "Own property in Thailand", "label_th": "บ้าน/คอนโด/ที่ดินในไทย"}, {"value": "spouse_children", "label_en": "Spouse or children in Thailand", "label_th": "คู่สมรสหรือบุตรอยู่ในไทย"}, {"value": "dependents", "label_en": "Dependents in Thailand", "label_th": "พ่อแม่หรือผู้ที่ต้องดูแลในไทย"}, {"value": "investments", "label_en": "Investments or other assets", "label_th": "เงินลงทุนหรือทรัพย์สินอื่น"}, {"value": "none", "label_en": "None of the above", "label_th": "ไม่มีข้อใดข้างต้น"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('contact_preference', 'q36', 'ต้องการให้เราติดต่อกลับทางไหน?', 'How to contact you?', 'radio', 'S6', 35, '''[{"value": "line", "label_en": "Via LINE OA @itinerry", "label_th": "ผ่าน LINE OA @itinerry"}, {"value": "call", "label_en": "Call me back", "label_th": "ให้โทรกลับ"}]''::jsonb', 't');
insert into public.visa_questionnaire (question_key, legacy_id, question_text_th, question_text_en, question_type, section, display_order, options, is_active) values ('callback_time', 'q37', 'ช่วงเวลาที่ต้องการให้ติดต่อกลับ', 'Preferred callback time', 'radio', 'S7', 36, '''[{"value": "morning", "label_en": "Morning 9:00–12:00", "label_th": "เช้า 9:00–12:00"}, {"value": "afternoon", "label_en": "Afternoon 12:00–15:00", "label_th": "บ่าย 12:00–15:00"}, {"value": "evening", "label_en": "Evening 15:00–18:00", "label_th": "เย็น 15:00–18:00"}]''::jsonb', 't');
